name: CI

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Gem audit
        run: bin/bundler-audit check --update

      - name: Brakeman audit
        run: bundle exec brakeman -i config/brakeman.ignore --quiet --no-pager --exit-on-warn --exit-on-error

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: open_construction_twin_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d open_construction_twin_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_TEST_NAME: open_construction_twin_test

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libvips curl gdal-bin

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Build JavaScript and CSS assets
        run: yarn build && yarn build:css

      - name: Prepare database and run tests
        run: bin/rails db:prepare && bin/rails test
